### ISSUE TITLE
The  rotation matrix for the normal map

### ISSUE THREAD

**Issue by HalleyJiang** [VCL3D/3D60#1]
https://github.com/VCL3D/3D60/blob/dacd8f0b0bdcbe4ec7239592a9bccd15f9bac3b4/ThreeD60/common.py#L103

Dear 3D60 authors,

Thanks for sharing the wonderful 3D60 dataset. I have questions on the rotation matrix for the normal map. 
First, in the rotation matrix of your code, the 2nd and 3rd rows are not orthogonal. 
Second, since the rotation is around the vertical direction, i.e., y-axis, I deduce the rotation matrix is

mat = [ [numpy.cos(theta),       0.0,                 -numpy.sin(theta)],\
             [0.0,                              1.0,                             0.0           ],\
             [numpy.sin(theta),        0.0,                  numpy.cos(theta)]]

I am not sure whether my calculation is correct or not.  Can you help me with my questions? Thanks.

**Comment by ankarako** [comment]
Hi @HalleyJiang,

Thank you for pointing this out. In fact the rotation matrix was indeed wrong (check the last commit). However, the rotation axis has to do with the dataset rendering and blender. Running my test scripts it seems to be right now.
Please, if you find any errors, do not hesitate to leave a comment.
Antonis

**Comment by HalleyJiang** [comment]
Hi Antonis,
Thanks. I just gave an inspection of the normal data. The coordinate frame of normal is different from the that one of camera. I eventually found that the rotation matrix in the code is correct.  
Hualie
