### ISSUE TITLE
How to deal with depth.exrfile

### ISSUE THREAD

**Issue by hahawhat-ch** [VCL3D/3D60#2]
Dear 3D60 authors：
     I'm just download your dataset ，Thank you ！I'm new in depth filed，so when I check the depth.exr file(with photoshop)，i'm confused，it looks like that different from the ground truth I  saw before，how can i deal with the depth.exr.Thank you

![BL@N8TYQTFA}M90TC}3H1M0](https://user-images.githubusercontent.com/68527698/107142888-cfe1d380-696c-11eb-8e09-f4a0266416a1.png)

**Comment by zuru** [comment]
You can use opencv-python to load it:
```
  depth = cv2.imread(filename, cv2.IMREAD_ANYDEPTH)
```

See also: https://github.com/VCL3D/3D60/blob/5d574cd84b957d406135bf7ce141f07b8d77ec70/ThreeD60/common.py#L86

External useful tools are: 
- The binaries at https://www.openexr.com/ (for displaying with an external viewer)
- Irfraview (https://www.irfanview.com/) with its plugins can also open `.exr` files for viewing
- Tev (https://github.com/Tom94/tev) is a similar tool that opens and shows `.exr` files.
